version: '3.7'
services:
  postgres:
    image: timescale/timescaledb-ha:pg13-latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: agridata

